# Generated by Django 5.0.6 on 2024-06-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='company_address',
            field=models.CharField(default='nyatsime', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='company_name',
            field=models.CharField(default='company', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='date_of_registration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employer',
            name='name',
            field=models.CharField(default='larry', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employer',
            name='registration_number',
            field=models.CharField(default='wertg', max_length=50),
            preserve_default=False,
        ),
    ]
