# Generated by Django 5.0.6 on 2024-07-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_employee_department_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='email',
            field=models.EmailField(default='g@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
