# Generated by Django 5.0.6 on 2024-07-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_employer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
