# Generated by Django 5.0.6 on 2024-07-09 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_employer_options_alter_employer_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='name',
        ),
    ]
