# Generated by Django 5.0.6 on 2024-07-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_employer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
